# Generated by Django 5.1 on 2024-08-15 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_department_profile_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='department',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
