# renew_before_expiry = 30 days
version = 2.8.0
archive_dir = /etc/letsencrypt/archive/services.pystart.by
cert = /etc/letsencrypt/live/services.pystart.by/cert.pem
privkey = /etc/letsencrypt/live/services.pystart.by/privkey.pem
chain = /etc/letsencrypt/live/services.pystart.by/chain.pem
fullchain = /etc/letsencrypt/live/services.pystart.by/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = d4ea4cf49a55a14cbb8f8e7c362a6ae1
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
services.pystart.by = /var/www/certbot
www.services.pystart.by = /var/www/certbot
