# Generated by Django 4.2.4 on 2023-09-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='nds',
            field=models.FloatField(blank=True, default=0, verbose_name='Из них НДС'),
        ),
    ]
