# Generated by Django 4.2.4 on 2023-09-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_reports_nds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='nds',
            field=models.FloatField(blank=True, verbose_name='Из них НДС'),
        ),
    ]
