# Generated by Django 4.1 on 2024-02-12 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_users_avatar_alter_users_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='avatar',
            field=models.ImageField(default='static/services/static/users/profiles/avatars/nophoto.jpg', upload_to='static/users/profiles/avatars', verbose_name='Аватар'),
        ),
    ]
