# Generated by Django 4.1 on 2024-02-14 20:19

from django.db import migrations, models
import services.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_users_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='avatar',
            field=models.ImageField(default='nophoto.jpg', null=True, upload_to=services.models.user_directory_path, verbose_name='Аватар'),
        ),
    ]
