# Generated by Django 4.1 on 2024-02-12 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=150, verbose_name='Имя, отчество')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.roles', verbose_name='Роль')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Structures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.users', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Структура',
                'verbose_name_plural': 'Структуры',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.FloatField(verbose_name='Стоимость')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.structures', verbose_name='Структура')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('amount', models.PositiveIntegerField(verbose_name='Количество')),
                ('sum', models.FloatField(verbose_name='Сумма')),
                ('nds', models.FloatField(blank=True, default=0, verbose_name='Из них НДС')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('date_edit', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.services', verbose_name='Услуга')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.structures', verbose_name='Структура')),
            ],
            options={
                'verbose_name': 'Отчет',
                'verbose_name_plural': 'Отчеты',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200, verbose_name='Имя клиента')),
                ('sum', models.FloatField(verbose_name='Сумма заказа')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail клиента')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон клиента')),
                ('date_of_receiving', models.DateTimeField(blank=True, verbose_name='Желаемая дата получения заказа')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий к заказу')),
                ('file', models.FileField(upload_to='uploads/ordersIBC/%Y/%m/%d/', verbose_name='Файл')),
                ('status', models.CharField(max_length=15, verbose_name='Статус заказа')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('date_edit', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.services', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
