# Generated by Django 4.2.4 on 2024-03-13 07:01

from django.db import migrations, models
import services.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='structures',
            name='earned',
            field=models.FloatField(default=0, verbose_name='Заработано'),
        ),
        migrations.AddField(
            model_name='structures',
            name='plan',
            field=models.FloatField(default=0, verbose_name='План'),
        ),
        migrations.AddField(
            model_name='users',
            name='avatar',
            field=models.ImageField(default='nophoto.jpg', null=True, upload_to=services.models.user_directory_path, verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=200, null=True, unique=True, verbose_name='email'),
        ),
    ]
