# Generated by Django 4.1 on 2024-02-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_users_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='avatar',
            field=models.ImageField(default='static/services/static/users/profiles/avatars/nophoto.jpg', upload_to='static/services/static/users/profiles/avatars', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=200, unique=True, verbose_name='email'),
        ),
    ]
