# Generated by Django 4.1 on 2024-02-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_users_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='avatar',
            field=models.ImageField(default='services/static/users/profiles/avatars/nophoto.jpg', upload_to='services/static/users/profiles/avatars', verbose_name='Аватар'),
        ),
    ]
