# Generated by Django 4.1 on 2024-02-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_users_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='structures',
            name='earned',
            field=models.FloatField(default=0, verbose_name='Заработано'),
        ),
        migrations.AddField(
            model_name='structures',
            name='plan',
            field=models.FloatField(default=0, verbose_name='План'),
        ),
    ]
